.TH pmr 1 "2004/02/27" Linux "user commands"

.SH NAME
pmr \- command line pipe measurement tool for Unixes

.SH SYNTAX
.B pmr
[\fB-l Bps\fR] [\fB-r\fR] [\fB-t secs\fR] [\fB-b size\fR] [\fB-v\fR]

.SH VERSION
This man page documents pmr version 0.07 and maybe later.

.SH DESCRIPTION
.I pmr
is a command line tool to measure bandwidth and amount of bytes going through
the pipe.

.SH OPTIONS
.TP
.BI \-l " Bps"
Limit throughput to a given bytes per second rate
.I Bps
.TP
.B \-r
Don't print new lines on output, use carriage return
.TP
.BI \-t " secs"
Display information once in every
.I secs
time interval
.TP
.BI \-b " size"
Use input buffer size of
.I size
bytes
.TP
.B \-h
Display help
.TP
.B \-v
Display version information


.SH EXAMPLES
.nf
Transfer SHELL_PATTERN files with netcat to a host:
.ft B
tar cvf - SHELL_PATTERN |pmr |nc host port

.ft R
Generate lots of context switches:
.ft B
pmr < /dev/zero |cat > /dev/zero


.SH AUTHOR
Heikki Orsila <heikki.orsila@iki.fi>
.br
