.TH pmr 1 "2006-11-03" Linux "user commands"

.SH NAME
pmr \- command line pipe measurement tool for Unixes

.SH SYNTAX
.B pmr
[\fB-l Bps\fR] [\fB-s size\fR] [\fB-m\fR] [\fB-r\fR] [\fB-t secs\fR] [\fB-b size\fR] [\fB-v\fR] FILE ...

.SH VERSION
This man page documents pmr version 0.12 and maybe later.

.SH DESCRIPTION
.I pmr
is a command line tool to measure bandwidth and amount of bytes going through
a command line pipe. It can also be used to limit pipe throughput in
bytes per second, compute an md5sum of the stream and compute
an ETA for completion.

If regular files are given as parameters, they are concatenated to the
standard output and an ETA is computed based on the total size of the files.

.SH OPTIONS
.TP
.B \-h
Display help
.TP
.B \-l Bps
Limit throughput to a given bytes per second rate
.I Bps .
One can use IEC or SI standard multipliers for
.I Bps
: KiB = 1024, MiB = 1024^2, ...; kB = 1000, MB = 10^6, ... The IEC or SI
multiplier must immediately follow the number. No whitespace is allowed
between the numeric and scaling part. All multipliers can be given as
shortened versions by giving only first two letters. Also, IEC multipliers
can be given with case-insensitive 2 letter versions: ki, mi, gi, ...

An example: pmr -l 64KiB < /dev/zero > /dev/null
.TP
.B \-m / \-\-md5
Compute an md5 checksum of the stream. This is useful for verifying data integrity through TCP networks.
.TP
.B \-r
Don't print new lines on output, use carriage return
.TP
.B \-s size
Calculate ETA given a size estimate. Giving regular files as pmr parameters
implies -s SUM, where SUM is the total size of those files.
.TP
.B \-t secs
Display information once in every
.I secs
time interval
.TP
.B \-v
Display version information

.SH USELESS OPTIONS
.TP
.B \-b size
Use input buffer size of
.I size
bytes
.TP
.B \-p
Makes pmr touch each 4k page it has read from the kernel. Useful when
benchmarking page copy speed with /dev/zero device.

.SH EXAMPLE 1
.nf
Transfer files with TCP from one host to another and simultaneously
verify data checksums with MD5:
.ft B
tar cv SHELL_PATTERN |pmr -m |nc host port

.ft R
The receiving end does:
.ft B
nc -l -p port |pmr -m |tar xv

.ft R
After the transfer, both ends can compare md5sums from pmr output, i.e. 
the last output line off stderr.

Optionally TCP transfer rate can be limited with -l.

.SH EXAMPLE 2
Generate lots of context switches:
.ft B
pmr < /dev/zero |cat > /dev/zero

.SH CONFORMING TO
The bandwidth is printed in IEC 60027-2 (2000-11) Ed. 2.0 recommended 
format (KiB, MiB, GiB, ...).

.SH AUTHOR
.B pmr
was written by Heikki Orsila <heikki.orsila@iki.fi>. His web page is
located at http://www.iki.fi/shd/
.br
