.TH pmr 1 "2006-11-03" Linux "user commands"

.SH NAME
pmr \- command line pipe measurement tool for Unixes

.SH SYNTAX
.B pmr
[\fB-l Bps\fR] [\fB-s size\fR] [\fB-m\fR] [\fB-e com\fR] [\fB-r\fR] [\fB-t secs\fR] [\fB-b size\fR] [\fB-v\fR] FILE ...

.SH VERSION
This man page documents pmr version 0.13 and maybe later.

.SH DESCRIPTION
.I pmr
is a command line tool to measure bandwidth and amount of bytes going through
a command line pipe. It can also be used to limit pipe throughput in
bytes per second, compute an md5sum of the stream and compute
an ETA for completion.

If regular files are given as parameters, they are concatenated to the
standard output and an ETA is computed based on the total size of the files.

pmr tries to read a configuration file at startup. It can be used to set a
specific default behavior. See CONFIGURATION FILE section.

.SH OPTIONS
.TP
.B \-e com args
Run command
.I com
with
.I args
, copy stdin of pmr to the stdin of he command, and copy stdout of the
command to the stdout of pmr. pmr acts as a measuring filter between the
shell and the command.
.TP
.B \-h
Display help
.TP
.B \-l Bps
Limit throughput to a given bytes per second rate
.I Bps .
One can use IEC or SI standard multipliers for
.I Bps
: KiB = 1024, MiB = 1024^2, ...; kB = 1000, MB = 10^6, ... The IEC or SI
multiplier must immediately follow the number. No whitespace is allowed
between the numeric and scaling part. All multipliers can be given as
shortened versions by giving only first two letters. Also, IEC multipliers
can be given with case-insensitive 2 letter versions: ki, mi, gi, ...

An example: pmr -l 64KiB < /dev/zero > /dev/null
.TP
.B \-m / \-\-md5
Compute an md5 checksum of the stream. This is useful for verifying data integrity through TCP networks.
.TP
.B \-r
Don't print new lines on output, use carriage return
.TP
.B \-s size
Calculate ETA given a size estimate. Giving regular files as pmr parameters
implies -s SUM, where SUM is the total size of those files.
.TP
.B \-t secs
Display information once in every
.I secs
time interval
.TP
.B \-v
Display version information

.SH USELESS OPTIONS
.TP
.B \-b size
Use input buffer size of
.I size
bytes

.SH CONFIGURATION FILE
pmr tries to read a configuration file at startup. It can be used to set a
specific default behavior. pmr first tries to read it from
$(HOME)/.pmr and second time from /etc/pmr. If configuration file is found,
it is read line by line. Lines beginning with # are comment lines.
Whitespace is ignored.

A line can contain 0 or 1 directives. Valid directives are:
.br
    carriage           (enable carriage return mode, see -r)
br
    limit rate         (set rate limit, see -l)
.br
    md5                (enable md5sum mode, see -m)
.br
    update t           (set update time interval, see -t)

.SH EXAMPLE 1
.nf
Transfer files with TCP from one host to another and simultaneously
verify data checksums with MD5:
.ft B
tar cv SHELL_PATTERN |pmr -m |nc host port

.ft R
The receiving end does:
.ft B
nc -l -p port |pmr -m |tar xv

.ft R
After the transfer, both ends can compare md5sums from pmr output, i.e. 
the last output line off stderr.

Optionally TCP transfer rate can be limited with -l.

.SH EXAMPLE 2
Generate lots of context switches:
.ft B
pmr < /dev/zero |cat > /dev/null

.ft R
Or optionally, use spawning mode:
.ft B
pmr -e cat < /dev/zero > /dev/null

.SH CONFORMING TO
The bandwidth is printed in IEC 60027-2 (2000-11) Ed. 2.0 recommended 
format (KiB, MiB, GiB, ...).

.SH FILES
.br
/etc/pmr (global configuration file)
.br
$(HOME)/.pmr (user-specific configuration file)

.SH AUTHOR
.B pmr
was written by Heikki Orsila <heikki.orsila@iki.fi>: http://www.iki.fi/shd/
.br
